# Generated by Django 3.0.6 on 2020-07-21 16:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product_pics'),
        ),
    ]
