# Generated by Django 3.0.6 on 2020-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200531_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
