# Generated by Django 3.0.6 on 2020-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20200610_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
