# Generated by Django 3.0.6 on 2020-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20200610_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
