# Generated by Django 3.0.6 on 2020-07-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0027_auto_20200720_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.AddField(
            model_name='cart',
            name='reference',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
