# Generated by Django 3.0.6 on 2020-07-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200721_1701'),
        ('carts', '0030_cart_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
